site_name: 圆头耄耋的书架

site_url: https://fwdzh.github.io  # 设置 GitHub Pages URL
# repo_url: https://github.com/fwdzh/fwdzh.github.io  # 设置 GitHub Repository URL
# repo_name: mkdocs material blog
remote_branch: gh-pages    # GitHub Pages 分支
remote_name: origin       # 远程仓库名

copyright: Copyright &copy; 理塘丁真

theme:
  name: material
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  language: zh
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.action.view
    - content.footnote.tooltips
    - content.tabs.link
    - header.autohide

    # - navigation.tabs.sticky
    # - navigation.sections 

    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path

    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    # - navigation.expand # 自动展开文件

    - toc.follow

    # - search.highlight
    # - search.share
    # - search.suggest
  # palette:
  #   scheme: default
  #   primary: indigo
  #   accent: indigo
  palette:
    # 亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white         # 使用白色作为主色
      accent: indigo        # 搭配靛青色作为强调色
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    
    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white         # 深色模式也使用白色
      accent: indigo        # 保持相同的强调色
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式

  font:
    false    # 禁用默认字体以使用自定义字体

  icon:
    logo: material/rocket-launch       # 火箭
    repo: fontawesome/brands/github        # 仓库图标
  favicon: assets/favicon.png
markdown_extensions:
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite

  - toc:
      permalink: true
      toc_depth: 6 # 控制目录最多显示几级标题
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
    
# plugins:
  # - search:
      # 搜索索引设置
      # lang: 
      #   - en
      #   - zh
      # separator: '[\s\-\.]+'    # 分词分隔符
  # - pagefind
  

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # - javascripts/nav.js
  # - javascripts/audio_player.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css
nav:
  - 首页: index.md
  - final:
    - P2607: cp_solving/final/P2607.md
  # - XCPC一百天:
  #   - 第 4 天: XCPC_100days/day004.md
  #   - 第 3 天: XCPC_100days/day003.md
  #   - 第 2 天: XCPC_100days/day002.md
  #   - 第 1 天: XCPC_100days/day001.md
  - XCPC:
    - 区域赛:
      - 第 10 届 CCPC 中国大学生程序设计竞赛郑州站: XCPC/Regional/2024Zhengzhou.md
      - 第 49 届 ICPC 国际大学生程序设计竞赛区域赛上海站: XCPC/Regional/2024Shanghai.md
      - 第 49 届 ICPC 国际大学生程序设计竞赛区域赛杭州站: XCPC/Regional/2024Hangzhou.md
    - 省赛&邀请赛:
      - 2025年icpc全国邀请赛（南昌）暨2025年（icpc）江西省大学生程序设计竞赛: XCPC/Invitational/25Nanchang.md
      - 第十三届陕西省国际大学生程序设计竞赛 - 正式赛: XCPC/Provincial/2025Shaanxi.md
      - 第十三届重庆市大学生程序设计竞赛: XCPC/Provincial/2025Chongqing.md
      - 2025年北京市大学生程序设计竞赛暨“小米杯”全国邀请赛: XCPC/Invitational/24Beijing.md
      - 第 49 届 ICPC 国际大学生程序设计竞赛邀请赛武汉站: XCPC/Invitational/24Wuhan.md
      - 2023年第五届河南省CCPC大学生程序设计竞赛: XCPC/Provincial/2023Henan.md
      - 2024 CCPC 全国邀请赛（山东）暨山东省大学生程序设计竞赛: XCPC/Invitational/24Shandong.md
      - 2024 年陕西省第十二届国际大学生程序设计竞赛省赛: XCPC/Provincial/2024Shaanxi.md
      - 2024年四川省大学生程序设计竞赛: XCPC/Provincial/2024Sichuan.md
    - 校赛:
      - 2024北京航空航天大学程序设计竞赛 决赛: XCPC/School/2024BUAA.md
      - 2025华中农业大学程序设计竞赛: XCPC/School/2025HZAU.md
    - 其他比赛:
      - Baozii Cup 2: XCPC/Others/Baozii_Cup2.md
    - 蓝桥杯:
      - 2025年蓝桥杯国赛B组 C/C++: XCPC/Lanqiao/2025/National/CPP_B.md
      - 2025年蓝桥杯省赛B组 C/C++: XCPC/Lanqiao/2025/Provincial/CPP_B.md
    - 2025“钉耙编程”中国大学生算法设计春季联赛:
        - 第四场: cp_solving/2025hdu-spring/04.md
        - 第三场: cp_solving/2025hdu-spring/03.md
        - 第一场: cp_solving/2025hdu-spring/01.md
    
  - 刷题记录: 
    # - 日常记录表:
    #   - 日常记录1: daily/table/01.md
    # - 100道洛谷蓝题:
    #   - index: cp_solving/100_blue/main.md
    #   - P1967 [NOIP 2013 提高组] 货车运输: cp_solving/100_blue/P1967.md
    #   - P1450 [HAOI2008] 硬币购物: cp_solving/100_blue/P1450.md
    #   - P3694 邦邦的大合唱站队: cp_solving/100_blue/P3694.md
    #   - P6088 [JSOI2015] 字符串树: cp_solving/100_blue/P6088.md
    - Codeforces Rating 1900+ 题目: cp_solving/2025/0420.md
    - 成长记录: cp_solving/0313.md
    - 动态规划练习: cp_solving/2025/0407.md
    - 部分做题记录: cp_solving/2025/0313.md
    - 2025年3月1日-3月9日: cp_solving/2025/0301.md
    - 1600-1800 day1-day4 : cp_solving/2.md
    - _1: cp_solving/1.md
  - contest:
    - Codeforces:
      - Atto Round 1 (Codeforces Round 1041, Div. 1 + Div. 2): cp_solving/Codeforces/2127.md
      - Educational Codeforces Round 180 (Rated for Div. 2): cp_solving/Codeforces/2112.md
      - Codeforces Round 1033 (Div. 2) and CodeNite 2025: cp_solving/Codeforces/2120.md
      - Educational Codeforces Round 179 (Rated for Div. 2): cp_solving/Codeforces/2111.md
      - Codeforces Round 1028 (Div. 2): cp_solving/Codeforces/2116.md
      - Codeforces Round 1022 (Div. 2): cp_solving/Codeforces/2108.md
      - Codeforces Round 1019 (Div. 2): cp_solving/Codeforces/2103.md
      - Codeforces Round 1018, Div. 1 + Div. 2: cp_solving/Codeforces/2096.md
      - Codeforces Round 1016 (Div. 3): cp_solving/Codeforces/2093.md
      - Codeforces Round 1015, Div. 1 + Div. 2: cp_solving/Codeforces/2084.md
      - Educational Codeforces Round 177: cp_solving/Codeforces/2086.md 
      - Codeforces Round 1014 (Div. 2): cp_solving/Codeforces/2092.md
      - Codeforces Round 1013 (Div. 3): cp_solving/Codeforces/2091.md
      - Codeforces Round 1012 (Div. 2): cp_solving/Codeforces/2090.md
      - Codeforces Round 1011 (Div. 2): cp_solving/Codeforces/2085.md
      - Educational Codeforces Round 176: cp_solving/Codeforces/2075.md
      - Codeforces Round 1010 (Div. 2) unrated: cp_solving/Codeforces/2082.md
      - Codeforces Round 1009 (Div. 3): cp_solving/Codeforces/2074.md
      - Codeforces Round 1008 (Div. 2): cp_solving/Codeforces/2078.md
      - Codeforces Round 1007 (Div. 2): cp_solving/Codeforces/2071.md
      - Educational Codeforces Round 175: cp_solving/Codeforces/2070.md
      - Codeforces Round 1006 (Div. 3): cp_solving/Codeforces/2072.md
      - Educational Codeforces Round 174: cp_solving/Codeforces/2069.md
      - Codeforces Round 1005 (Div. 2): cp_solving/Codeforces/2064.md
    - Codeforces VP:
      - Educational Codeforces Round 149: cp_solving/Codeforces/1837.md
      - Educational Codeforces Round 150: cp_solving/Codeforces/1841.md
    - Atcoder:
      - Atcoder Beginner Contest 402: cp_solving/AtCoder/ABC402.md
      - Atcoder Beginner Contest 398: cp_solving/AtCoder/ABC398.md
      - Atcoder Beginner Contest 397: cp_solving/AtCoder/ABC397.md
      - Atcoder Beginner Contest 395: cp_solving/AtCoder/ABC395.md
    - Nowcoder:
      - 牛客周赛 Round 82: cp_solving/nowcoder/102303.md

  - 日常:
    - CF2117G + 23合肥区域赛J: daily/2025/0801.md
    - 新的开始: daily/2025/0630.md
    - 2025-04-05: daily/2025/0405.md
    - 2025-04-01: daily/2025/0401.md
    - 2025-03-31: daily/2025/0331.md
    - 2025-03-27/28: daily/2025/0327.md
    - 2025-03-18: daily/2025/0318.md
    - 2025-03-12: daily/2025/0312.md
    - 2025-03-11: daily/2025/2025_0311.md
    - 2025-02-15: daily/2025/2025_0215.md
    - 2025-01-18: daily/2025/2025_0118.md
  - Algorithm:
    - 字符串:
      - 字典树: algorithm/string/trie.md
      - KMP: algorithm/string/KMP.md
    - 数据结构:
      - ST 表: algorithm/datastructure/sparse-table.md
      - 树状数组: algorithm/datastructure/Fenwick.md
      - 笛卡尔树: algorithm/datastructure/Cartesian-tree.md
      - 线段树: 
        - 线段树基础: algorithm/datastructure/SegmentTree/SegmentTree.md
        - 线段树合并: algorithm/datastructure/SegmentTree/seg-merge.md
      - 莫队算法: algorithm/datastructure/mo-algo.md
    - 数论:
      - 数论基础: algorithm/numbertheory/basic.md
    - 数学:
      - 组合数学:
        - 排列组合: algorithm/math/combinatorics/combination.md
      - 线性代数:
        - 矩阵: algorithm/math/linear-algebra/matrix.md
    - 图论:
      - 强连通分量: algorithm/graph/scc.md
      - 树链剖分: algorithm/graph/HLD.md
      - 二分图: algorithm/graph/BipartiteGraph.md
    - 其他:
      - 对拍: algorithm/others/duipai.md
      - VScode Snippets: algorithm/others/snippets.md
  # - 开发:
  #   - 前端: develepment/frontend/main.md
  - 杂项:
    - github基础操作及github pages: misc/gitbasic.md
    - windows双系统删除ubuntu arch: misc/deleteubuntu.md
    - windows创建恢复分区: misc/winrecovery.md
    - github相关: misc/git_.md
    - material for MkDocs: misc/MkDocs.md
    - 生成指定难度数量的随机CF题目: misc/rndcfproblem.md
    - 通过自定义域名访问github pages: misc/customdomain.md
    - win vscode配置: misc/vscodesetting.md
  - About:
    - 关于我: about/me.md
    - 友情链接: about/links.html
  # - 页面更新:
  #   - main: update/20250115.md
