site_name: wuyi
theme:
    name: material
nav:
  - 首页: index.md
  - 刷题:
    - Codeforces:
      - Round 996 (Div.2): cp_solving/Codeforces/2055/main.md
      # docs cp_solving/Codeforces/2055/main.md
  - 杂项:
    - 博客相关:
      - material for MkDocs: misc/MkDocs.md
# mkdocs.yml
site_url: https:fwdzh.github.io  # 设置 GitHub Pages URL
remote_branch: gh-pages    # GitHub Pages 分支
remote_name: origin       # 远程仓库名