# .github/workflows/deploy.yml

name: Deploy Documentation
on:
  # 触发条件
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main

  # 允许手动触发
  workflow_dispatch:

# 环境变量
env:
  PYTHON_VERSION: '3.10'
  DEPLOY_BRANCH: gh-pages

# 任务定义
jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的git历史用于最近更新时间

      # 设置Python环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      # 缓存依赖
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 安装依赖
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 配置Git
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # 构建文档
      - name: Build Documentation
        run: |
          mkdocs build --clean --verbose

      # 优化资源
      - name: Optimize Assets
        run: |
          # 压缩图片
          find site/ -type f -name "*.png" -exec optipng -o5 {} \;
          find site/ -type f -name "*.jpg" -exec jpegoptim --strip-all {} \;

          # 压缩JavaScript和CSS
          find site/ -type f -name "*.js" -exec uglifyjs {} -o {} \;
          find site/ -type f -name "*.css" -exec cleancss -o {} {} \;

      # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # 只在main分支部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: ${{ env.DEPLOY_BRANCH }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          full_commit_message: |
            Deploy Documentation

            Commit: ${{ github.sha }}
            Workflow: ${{ github.workflow }}

            ${{ github.event.head_commit.message }}

      # 部署完成通知
      - name: Deployment Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.runId;
            const run_url = `https://github.com/${owner}/${repo}/actions/runs/${run_id}`;

            if (context.job.status === 'success') {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: context.issue.number,
                body: `✅ Documentation deployed successfully!\nPreview: https://${owner}.github.io/${repo}/\nWorkflow: ${run_url}`
              });
            } else {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: context.issue.number,
                body: `❌ Documentation deployment failed.\nSee details: ${run_url}`
              });
            }

# 错误追踪和报告
      - name: Report Errors
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.runId;

            await github.rest.issues.create({
              owner,
              repo,
              title: `🔴 Documentation deployment failed - ${new Date().toISOString()}`,
              body: `Deployment failed for commit: ${context.sha}\n\nSee workflow run: https://github.com/${owner}/${repo}/actions/runs/${run_id}\n\nPlease check the logs for more details.`,
              labels: ['deployment', 'bug']
            });